Global:
  rec_inference_model_dir: "./models/cartoon_rec_ResNet50_iCartoon_v1.0_infer/"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 100
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

RecPreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:

RecPostProcess: null

# indexing engine config
IndexProcess:
  index_path: "./dataset/cartoon_demo_data_v1.0/index/"
  image_root: "./dataset/cartoon_demo_data_v1.0/"
  data_file:  "./dataset/cartoon_demo_data_v1.0/data_file.txt"
  delimiter: "\t"
  dist_type: "IP"
  pq_size: 100
  embedding_size: 2048
