# global configs
Trainer:
  name: TrainerReID
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  class_num: 3000
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 160
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: "./inference"
  num_split: 15
  feature_normalize: True


# model architecture
Arch:
  name: "RecModel"
  Backbone: 
    name: "ResNet50_last_stage_stride1"
    pretrained: True
  BackboneStopLayer:
    name: "adaptive_avg_pool2d_0"
  Neck:
    name: "VehicleNeck"
    in_channels: 2048
    out_channels: 512
  Head:
    name: "CircleMargin"
    margin: 0.35
    scale:  64
 
# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
    - PairwiseCosface:
        margin: 0.35 
        gamma: 64
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.01
  regularizer:
    name: 'L2'
    coeff: 0.0001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
        name: LogoDataset
        image_root: "dataset/LogoDet-3K-crop/train/"
        cls_label_path: "dataset/LogoDet-3K-crop/LogoDet-3K+train.txt"
        transform_ops:
          - ResizeImage:
              size: 224
          - RandFlipImage:
              flip_code: 1
          - AugMix:
              prob: 0.5
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
          - RandomErasing:
              EPSILON: 0.5
    sampler:
        name: DistributedRandomIdentitySampler
        batch_size: 128
        num_instances: 2
        drop_last: False
        
    loader:
        num_workers: 6
        use_shared_memory: False


  Query:
    # TOTO: modify to the latest trainer
    dataset: 
        name: LogoDataset
        image_root: "dataset/LogoDet-3K-crop/val/"
        cls_label_path: "dataset/LogoDet-3K-crop/LogoDet-3K+val.txt"
        transform_ops:
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
    sampler:
        name: DistributedBatchSampler
        batch_size: 128
        drop_last: False
        shuffle: False
    loader:
        num_workers: 6
        use_shared_memory: False

  Gallery:
    # TOTO: modify to the latest trainer
    dataset: 
        name: LogoDataset
        image_root: "dataset/LogoDet-3K-crop/train/"
        cls_label_path: "dataset/LogoDet-3K-crop/LogoDet-3K+train.txt"
        transform_ops:
          - ResizeImage:
              size: 224
          - NormalizeImage:
              scale: 0.00392157
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: ''
    sampler:
        name: DistributedBatchSampler
        batch_size: 128
        drop_last: False
        shuffle: False
    loader:
        num_workers: 6
        use_shared_memory: False

