# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1000
  eval_during_train: True
  eval_interval: 1000
  start_eval_iter: 1
  epochs: 1
  iters: &max_iters 35000
  print_batch_step: 20
  use_visualdl: False
  eval_mode: retrieval
  retrieval_feature_from: features # 'backbone' or 'features'
  re_ranking: False
  # used for static mode and model export
  image_shape: [3, 256, 128]
  save_inference_dir: ./inference

# model architecture
Arch:
  name: RecModel
  infer_output_key: features
  infer_add_softmax: False
  Backbone:
    name: ResNet50_adaptivemaxpool
    pretrained: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/others/resnet50-19c8e357_torch2paddle.pdparams
    stem_act: null
  BackboneStopLayer:
    name: flatten
  Neck:
    name: FC
    embedding_size: 2048
    class_num: &feat_dim 128
    weight_attr:
      initializer:
        name: KaimingNormal
        fan_in: *feat_dim
        negative_slope: 0.0
        nonlinearity: leaky_relu
    bias_attr:
      initializer:
        name: Constant
        value: 0.0

# loss function config for traing/eval process
Loss:
  Train:
    - ContrastiveLoss_XBM:
        weight: 1.0
        margin: 0.5
        feat_dim: *feat_dim
        normalize_feature: True
        epsilon: 1.0e-5
        feature_from: features
        start_iter: 1000
        xbm_size: 55000
        xbm_weight: 1.0
  Eval:
    - ContrastiveLoss:
        weight: 1.0
        margin: 0.5
        feat_dim: *feat_dim
        normalize_feature: True
        epsilon: 1.0e-5
        feature_from: features

Optimizer:
  name: Adam
  lr:
    name: ReduceOnPlateau
    learning_rate: 0.0001
    mode: max
    factor: 0.1
    patience: 4
    threshold: 0.001
    threshold_mode: rel
    cooldown: 2
    min_lr: 0.000005
    epsilon: 1e-8
  regularizer:
    name: L2
    coeff: 0.0005

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: Market1501
      image_root: /workspace/hesensen/XBM_reprod/SOP
      cls_label_path: /workspace/hesensen/XBM_reprod/SOP/train_list.txt
      backend: pil
      transform_ops:
        - Resize:
            size: 256
        - RandomResizedCrop:
            scale: [0.2, 1]
            size: 224
        - RandomHorizontalFlip:
            prob: 0.5
        - ToTensor:
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
    sampler:
      name: DistributedRandomIdentitySampler
      batch_size: 64
      num_instances: 4
      drop_last: False
      shuffle: True
      max_iters: 35001
    loader:
      num_workers: 8
      use_shared_memory: True
  Eval:
    Query:
      dataset:
        name: Market1501
        image_root: /workspace/hesensen/XBM_reprod/SOP
        cls_label_path: /workspace/hesensen/XBM_reprod/SOP/test_list.txt
        backend: pil
        transform_ops:
          - Resize:
              size: 256
          - CenterCrop:
              size: 224
          - ToTensor:
          - Normalize:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
      sampler:
        name: DistributedBatchSampler
        batch_size: 256
        drop_last: False
        shuffle: False
      loader:
        num_workers: 8
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}
