Global:
  model_dir: SwinTransformer_base_patch4_window7_224_infer
  model_filename: inference.pdmodel
  params_filename: inference.pdiparams
  batch_size: 32
  input_name: inputs

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - softmax_48.tmp_0
QuantAware:
  use_pact: true
  activation_bits: 8
  is_full_quantize: false
  onnx_format: True
  activation_quantize_type: moving_average_abs_max
  weight_quantize_type: channel_wise_abs_max
  not_quant_pattern:
  - skip_quant
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
  - matmul
  - matmul_v2
  weight_bits: 8
TrainConfig:
  epochs: 1
  eval_iter: 500
  learning_rate: 
    type: CosineAnnealingDecay 
    learning_rate: 0.015
  optimizer_builder:
    optimizer:
      type: Momentum
    weight_decay: 0.00002
  origin_metric: 0.83
