mode: 'train'
ARCHITECTURE:
    name: 'ResNet50_vd'

checkpoints: ""
pretrained_model: "./pretrained/ResNet50_vd_ssld_pretrained"
model_save_dir: "./output/"
classes_num: 100
total_images: 50000
save_interval: 1
validate: True
valid_interval: 1
epochs: 100
topk: 5
image_shape: [3, 32, 32]
use_mix: False

LEARNING_RATE:
    function: 'Cosine'          
    params:                   
        lr: 0.04

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.0001

TRAIN:
    batch_size: 1024
    num_workers: 4
    file_list: "./dataset/CIFAR100/train_list.txt"
    data_dir: "./dataset/CIFAR100/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 32
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

    mix:
        - MixupOperator:
            alpha: 0.2


VALID:
    batch_size: 256
    num_workers: 0
    file_list: "./dataset/CIFAR100/test_list.txt"
    data_dir: "./dataset/CIFAR100/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 36
        - CropImage:
            size: 32
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
